import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import StandupInput from '../components/standup-input'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Easy Standup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Easy Standup
        </h1>

        <p className={styles.description}>
          Daily updates made simple.
        </p>


        <div className={styles.grid}>
            <StandupInput />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/mttchpmn"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with love by @mttchpmn
        </a>
      </footer>
    </div>
  )
}

export default Home
